# Generated by Django 4.0.3 on 2022-03-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_detail_user_detail_email_detail_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='prefer',
            new_name='hangout',
        ),
    ]
