# Generated by Django 4.0.3 on 2022-03-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_detail_facebook_detail_insta_detail_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='facebook',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='insta',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='twitter',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
