# Generated by Django 4.0.3 on 2022-03-12 15:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_matchrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
